trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Hello, world!
    - bash: echo 'Pipeline Level Variable = $(PipelineLevelVariable)'
      displayName: 'Run a one-line script'
  - job: SecondJob
    steps:  
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
- stage: DevDeploy
  dependsOn: Build
  variables: {enviroment: Dev}
  jobs:
  - job: DevDeployJob
    steps:
    - script: echo $(environment)DeployJob is running
      displayName: 'Run a one-line script'
- stage: QaDeploy
  dependsOn: Build
  jobs:
  - job: QaDeployJob
    variables: {environment: Qa}
    steps:
    - script: echo $(environment)DeployJob is running
      displayName: 'Run a one-line script'
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QaDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - script: echo ProdDeployJob is running
      displayName: 'Run a one-line script'

