trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Hello, world!
    - bash: echo 'Pipeline Level Variable = $(PipelineLevelVariable)'
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.Repository.LocalPath)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
#   - job: SecondJob
#     steps:  
#     - script: |
#         echo Add other tasks to build, test, and deploy your project.
#         echo See https://aka.ms/yaml
#       displayName: 'Run a multi-line script'
# - stage: DevDeploy
#   dependsOn: Build
#   variables:            #stage level variable
#     environment: Dev
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - script: echo $(environment)DeployJob is running
#       displayName: 'Run a one-line script'
# - stage: QaDeploy
#   dependsOn: Build
#   jobs:
#   - job: QaDeployJob
#     variables:          #job level variable
#       environment: Qa
#     steps:
#     - script: echo $(environment)DeployJob is running
#       displayName: 'Run a one-line script'
# - stage: ProdDeploy
#   dependsOn:
#   - DevDeploy
#   - QaDeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - script: echo ProdDeployJob is running
#       displayName: 'Run a one-line script'

